language: ruby
rvm:
  - 2.1.3
env:
  - RAILS_ENV=test SECRET_TOKEN=264e6709224405956c0738fbc151cca4fe89035c39c7a87015e375a480dcb3ccb88dd7633efbfc99edc959dcbffad3d8a225a9de981b5e9fa7d75137a145a749
services: postgresql
bundler_args: --without production
before_script:
  - psql -c 'create database promptly_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:schema:load
script: bundle exec rake spec
notifications:
  webhooks: http://cfa-project-monitor.herokuapp.com/projects/e794be6b-2609-4246-b34a-6b20eb79b2c0/status
  slack: postcode:H2UZeySMZDDB927JDoldOkSx